/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tw.cn.gtb;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

public class App {

    static final String TASK_FILE = System.getProperty("user.home") + File.separator + ".todo" + File.separator + "tasks";

    public static void main(String[] args) {
        throw new UnsupportedOperationException();
    }

    public List<String> run() {
        try {
            return Files.readAllLines(Path.of(TASK_FILE));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
